# Generated by Django 3.2.13 on 2022-06-08 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='template')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('content', models.TextField(verbose_name='content')),
                ('language', models.CharField(choices=[('EN', 'English'), ('PT', 'Portugues')], default='PT', max_length=10, verbose_name='language')),
                ('help_context', models.JSONField(blank=True, default=dict, help_text='{"username": "Name of user in hello expression"}', null=True, verbose_name='Help Context')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('title', 'language')},
            },
        ),
    ]
