# Generated by Django 3.2.13 on 2022-06-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='created',
        ),
        migrations.AlterField(
            model_name='template',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='template',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('PT', 'Portugues')], default='PT', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='template',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Template'),
        ),
    ]
