# Generated by Django 3.2.13 on 2022-06-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates_manager', '0002_auto_20220619_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='modified',
            new_name='created',
        ),
    ]
